spring:
  application:
    name: book-management-api
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/books}
    username: ${DB_USER:books}
    password: ${DB_PASSWORD:books}
  jooq:
    sql-dialect: POSTGRES
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-null-for-primitives: true
      fail-on-numbers-for-enums: true
      accept-float-as-int: false
server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
  error:
    include-message: never
    include-stacktrace: never
